export { default as Navbar} from './navbar/Navbar'
export { default as Hero } from './hero/Hero'
export { default as About } from './about/About'
export { default as Skills } from './skills/Skills'
export { default as Contact } from './contact/Contact'
export { default as Footer } from './footer/Footer'